<h1>Python Lesson 44</h1>
<img src="PythonLesson44TitleSlide.png" />

<img src="PythonLesson44LearningObjectives.png" />

<img src="PythonLesson44LinearAlgebraApplications.png" width="1200" />

<img src="PythonLesson44IntroToLinearAlgebra.png" />

<img src="PythonLesson44DataLinearAlgebra.png" />

<img src="PythonLesson44Matrix.png" />

In [12]:
# Create a 3 x 3 matrix of random integers between 1 and 10

# You only need to import a library or module once in your Jupyter Notebook.
# numpy is commonly aliased as np.  It's not required but recommended.
import numpy as np

# Use np.random.randint(min, max, size=(rows, cols))

m = np.random.randint(1, 11, size=(3, 3))
print(m)

m2 = np.array([[1, 2, 2],[2, 5, 7], [2, 7, 9]]) # another method for creating a matrix
print(m2)
print(m2.shape)

[[ 3  7 10]
 [ 7  2  6]
 [ 4  8  5]]
[[1 2 2]
 [2 5 7]
 [2 7 9]]
(3, 3)


<img src="PythonLesson44Vectors.png" />

<img src="PythonLesson44SimpleVector.png" />

In [3]:
# Create a row vector
rowVector = np.array([1, 2, 3])
print(f'row vector: {rowVector}')

# Create a column vector
columnVector = np.array([[1], [2], [3]])
print(f'column vector:\n {columnVector}')

row vector: [1 2 3]
column vector:
 [[1]
 [2]
 [3]]


<img src="PythonLesson44Scalars.png" />

In [12]:
# Calculate the area of a rectangle.  The length, width, and area are all scalars.


l = 12 # length 
w = 8 # width
a = l * w  # area of a rectangle

print(f"The area of a rectangle with a length of {l} and a width of {w} is {a}.")

The area of a rectangle with a length of 12, and a width of 8, is 96.


In [6]:
# Vector math

# Creating vectors
v1 = np.array([1, 2, 3]) # Is this a row or column vector?
v2 = np.array([4, 5, 6])

# Vector addition
vSum = v1 + v2
print("Sum:", vSum)  # Output: Sum: [5 7 9]

# Vector subtraction
vSubtract = v2 - v1
print("Difference:", vSubtract)  # Output: Difference: [3 3 3]




Sum: [5 7 9]
Difference: [3 3 3]


In [7]:
# Scalar multiplication
scalar = 2
vector_scaled = v1 * scalar
print("Scaled Vector:", vector_scaled)  # Output: Scaled Vector: [2 4 6]

# Dot product
dot_product = np.dot(v1, v2)
print("Dot Product:", dot_product)  # Output: Dot Product: 32


Scaled Vector: [2 4 6]
Dot Product: 32


<img src="PythonLesson44MatrixOperations.png" />

<img src="PythonLesson44MatrixAddition.png" />

In [24]:
# Create two matrices and add them to create a new matrix

matrix1 = np.array([[2, -1, 5],[10, 3, 1], [-7, 0, 3]])
print(matrix1)

matrix2 = np.array([[3, 2, 9],[-7, -7, 6], [1, 2, -4]])
print(matrix1)

matrix3 = matrix1 + matrix2
print(matrix3)

[[ 2 -1  5]
 [10  3  1]
 [-7  0  3]]
[[ 2 -1  5]
 [10  3  1]
 [-7  0  3]]
[[ 5  1 14]
 [ 3 -4  7]
 [-6  2 -1]]


<img src="PythonLesson44MatrixSubtraction.png" />

In [27]:
matrix4 = np.array([[5, -9],[0, 2], [0, 4]])
matrix5 = np.array([[3, 0],[6, -5], [2, 5]])
matrix6 = matrix4 - matrix5
print(matrix6)

[[ 2 -9]
 [-6  7]
 [-2 -1]]


<img src="PythonLesson44ScalarMultiplication.png" />

In [30]:
matrix7 = np.array([[4, 0, 3],[-7, 1, 2]])
print(matrix7)
print("Multiply matrix by 2:")
print(matrix7 * 2)

print("Multiply matrix by 1/2:")
print(matrix7 * 0.05)

print("Multiply matrix by -1:")
print(matrix7 * -1)



[[ 4  0  3]
 [-7  1  2]]
Multiply matrix by 2:
[[  8   0   6]
 [-14   2   4]]
Multiply matrix by 1/2:
[[ 0.2   0.    0.15]
 [-0.35  0.05  0.1 ]]
Multiply matrix by -1:
[[-4  0 -3]
 [ 7 -1 -2]]


<img src="PythonLesson44MatrixMultiplication.png" />

In [8]:
matrix8 = np.array([[1, 2, 2],[2, 5, 7],[2, 7, 9]])
print(matrix8)
matrix9 = np.array([[7, 4, 2],[6, 8, 1],[3, 7, 8]])
print(matrix9)
matrix10 = matrix8 * matrix9
print(matrix10)

[[1 2 2]
 [2 5 7]
 [2 7 9]]
[[7 4 2]
 [6 8 1]
 [3 7 8]]
[[ 7  8  4]
 [12 40  7]
 [ 6 49 72]]


In [39]:
matrix11 = np.array([[1, 2, 2],[2, 5, 7]])
matrix12 = np.array([[7, 4],[6, 8],[3, 7]])

matrix13 = np.matmul(matrix11, matrix12)
print(matrix13)

[[25 34]
 [65 97]]


<img src="PythonLesson44DotProductVector.png" />

In [41]:
vector1 = np.array([5, 6, -7])
print(vector1)

vector2 = np.array([-1, 2, -5])
print(vector2)

vector_dp = np.dot(vector1, vector2)
print(vector_dp)

[ 5  6 -7]
<class 'numpy.ndarray'>
[-1  2 -5]
<class 'numpy.ndarray'>
42


<img src="PythonLesson44MatrixTranspose.png" />

<img src="PythonLesson44MatrixTransposeExample.png" />

In [43]:
matrix14 = np.array([[1, 9, -6], [5, 3, -7]])
print(matrix14)

print("--------")

matrix14T = matrix14.T
print(matrix14T)

[[ 1  9 -6]
 [ 5  3 -7]]
--------
[[ 1  5]
 [ 9  3]
 [-6 -7]]


In [9]:
from IPython.display import IFrame, display

# Example: Embed the Wikipedia homepage
iframe = IFrame("https://www.mathsisfun.com/algebra/matrix-determinant.html", width=900, height=500)
display(iframe)

In [11]:
matrix15 = np.array([[3, 8], [4, 6]])
print(matrix15)

matrix15det = np.linalg.det(matrix15)
print(f"The determinant of matrix 15 is {matrix15det.round()}")

[[3 8]
 [4 6]]
The determinant of matrix 15 is -14.0
